//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioTI2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Defectos = new HashSet<Defectos>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int IdProducto { get; set; }
        public string DeviceName { get; set; }
        public int IdTipoProducto { get; set; }
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
        public int Precio { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> fecha_Ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defectos> Defectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Tipos_Productos Tipos_Productos { get; set; }
    }
}
