//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioTI2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suministros
    {
        public int IdSuministro { get; set; }
        public string Descripcion { get; set; }
        public int IdProveedor { get; set; }
        public Nullable<int> Precio { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
