//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioTI2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int IdVenta { get; set; }
        public int IdInventario { get; set; }
        public int IdCliente { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
