//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Ingresos
    {
        public int Ingreso_ID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Responsable_ID { get; set; }
        public Nullable<int> Cuenta_ID { get; set; }
        public Nullable<int> Iglesia_ID { get; set; }
    }
}
