//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Categorias_Iglesias
    {
        public int Categoria_Iglesia_ID { get; set; }
        public string Categoria_Iglesia { get; set; }
    }
}
