//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioTI.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimientos()
        {
            this.Inventario = new HashSet<Inventario>();
        }
    
        public decimal MovimientoID { get; set; }
        public Nullable<decimal> TipoMovimientoID { get; set; }
        public Nullable<decimal> BodegaID { get; set; }
        public Nullable<decimal> UbicacionID { get; set; }
        public Nullable<decimal> EmpleadoID { get; set; }
    
        public virtual Bodegas Bodegas { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual TiposMovimientos TiposMovimientos { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
