//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPTO
    {
        public int ID_DEPTO { get; set; }
        public string NOMBRE_DEPTO { get; set; }
        public int ID_AGENCIA { get; set; }
        public string USUARIO_RESPONSABLE { get; set; }
        public string ESTADO { get; set; }
    
        public virtual AGENCIA AGENCIA { get; set; }
        public virtual ENCABEZADO_CONTROL_EI ENCABEZADO_CONTROL_EI { get; set; }
        public virtual ENCABEZADO_CONTROL_ME ENCABEZADO_CONTROL_ME { get; set; }
        public virtual ENCABEZADO_DPME ENCABEZADO_DPME { get; set; }
    }
}
