//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_TOMAEI
    {
        public int No_Inventario { get; set; }
        public string Departamento { get; set; }
        public string Usuario_Responsable { get; set; }
        public System.DateTime Fecha_Toma_Inventario { get; set; }
        public string Codigo_Inventario { get; set; }
    }
}
