//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONTROL_EI
    {
        public int ID_DEPTO { get; set; }
        public int NUMERO_REFERENCIA { get; set; }
        public string CODIGO_INVENTARIO { get; set; }
        public System.DateTime FECHA_COMPRA { get; set; }
        public Nullable<System.DateTime> MES_DEPRECIACION { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public int ID_TIPO_EQUIPO { get; set; }
        public int ID_MARCA { get; set; }
        public string COLOR { get; set; }
        public string MODELO { get; set; }
        public string NUMERO_SERIE { get; set; }
        public string TIPO_PROCESADOR { get; set; }
        public string DISQUETERA { get; set; }
        public string LECTOR_DVD { get; set; }
        public string LECTOR_SD_MMC { get; set; }
        public string PARLANTES_EXTERNOS { get; set; }
        public string MONITOR_COLOR { get; set; }
        public string MONITOR_SERIE { get; set; }
        public string MONITOR_TAMANIO { get; set; }
        public string MONITOR_TIPO { get; set; }
        public string TECLADO_COLOR { get; set; }
        public string TECLADO_MODELO { get; set; }
        public string MOUSE_COLOR { get; set; }
        public string UBICACION { get; set; }
        public int ID_EMPLEADO { get; set; }
        public string CONDICION_ACTUAL { get; set; }
        public string USUARIO_RESPONSABLE { get; set; }
        public string ESTADO { get; set; }
    }
}
