//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DPME
    {
        public int ID_DEPTO { get; set; }
        public int NUMERO_REFERENCIA { get; set; }
        public string CODIGO_INVENTARIO { get; set; }
        public System.DateTime FECHA_COMPRA { get; set; }
        public Nullable<int> MESES { get; set; }
        public string NUM_CKE { get; set; }
        public string NUM_PDA { get; set; }
        public decimal COSTO { get; set; }
        public Nullable<decimal> PORCIENTO { get; set; }
        public Nullable<decimal> COSTO_PORCIENTO { get; set; }
        public int VIDA { get; set; }
        public Nullable<decimal> D_MES { get; set; }
        public Nullable<decimal> ACUMULADA { get; set; }
        public Nullable<decimal> VALOR_LIBROS { get; set; }
        public string DEPRECIADO { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ENCABEZADO_DPME ENCABEZADO_DPME { get; set; }
    }
}
