//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCABEZADO_CONTROL_ME
    {
        public int ID_DEPTO { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string USUARIO_RESPONSABLE { get; set; }
    
        public virtual DEPTO DEPTO { get; set; }
    }
}
