//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCABEZADO_DPME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCABEZADO_DPME()
        {
            this.DETALLE_DPME = new HashSet<DETALLE_DPME>();
        }
    
        public int ID_DEPTO { get; set; }
        public string NUMERO_CUENTA { get; set; }
        public System.DateTime FECHA_DEPRECIACION { get; set; }
        public string USUARIO_RESPONSABLE { get; set; }
    
        public virtual DEPTO DEPTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_DPME> DETALLE_DPME { get; set; }
    }
}
