//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCABEZADO_DPEI
    {
        public int ID_DEPTO { get; set; }
        public string NUMERO_CUENTA { get; set; }
        public System.DateTime FECHA_DEPRECIACION { get; set; }
        public string USUARIO_RESPONSABLE { get; set; }
    }
}
