//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_INV_ACTIVOSEntities : DbContext
    {
        public BD_INV_ACTIVOSEntities()
            : base("name=BD_INV_ACTIVOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENCIA> AGENCIA { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DEPTO> DEPTO { get; set; }
        public virtual DbSet<DETALLE_CONTROL_EI> DETALLE_CONTROL_EI { get; set; }
        public virtual DbSet<DETALLE_CONTROL_ME> DETALLE_CONTROL_ME { get; set; }
        public virtual DbSet<DETALLE_DPEI> DETALLE_DPEI { get; set; }
        public virtual DbSet<DETALLE_DPME> DETALLE_DPME { get; set; }
        public virtual DbSet<DETALLE_TOMA_ME> DETALLE_TOMA_ME { get; set; }
        public virtual DbSet<DETALLE_TOMAEI> DETALLE_TOMAEI { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<ENCABEZADO_CONTROL_EI> ENCABEZADO_CONTROL_EI { get; set; }
        public virtual DbSet<ENCABEZADO_CONTROL_ME> ENCABEZADO_CONTROL_ME { get; set; }
        public virtual DbSet<ENCABEZADO_DPED> ENCABEZADO_DPED { get; set; }
        public virtual DbSet<ENCABEZADO_DPEI> ENCABEZADO_DPEI { get; set; }
        public virtual DbSet<ENCABEZADO_DPME> ENCABEZADO_DPME { get; set; }
        public virtual DbSet<ENCABEZADO_TOMAEI> ENCABEZADO_TOMAEI { get; set; }
        public virtual DbSet<MARCAS> MARCAS { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIO { get; set; }
        public virtual DbSet<OPERACIONES> OPERACIONES { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<ROL_OPERACION> ROL_OPERACION { get; set; }
        public virtual DbSet<TIPO_CONTROL> TIPO_CONTROL { get; set; }
        public virtual DbSet<TIPO_EQUIPO> TIPO_EQUIPO { get; set; }
        public virtual DbSet<TIPO_EQUIPO_OFICINA> TIPO_EQUIPO_OFICINA { get; set; }
        public virtual DbSet<SegUsuario> SegUsuario { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual ObjectResult<Nullable<int>> CodeCorrelaticoME()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CodeCorrelaticoME");
        }
    
        public virtual ObjectResult<Nullable<int>> CodeCorrelativoEI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CodeCorrelativoEI");
        }
    
        public virtual int ELIMINAR_EI(string cODIGOINVENTARIO)
        {
            var cODIGOINVENTARIOParameter = cODIGOINVENTARIO != null ?
                new ObjectParameter("CODIGOINVENTARIO", cODIGOINVENTARIO) :
                new ObjectParameter("CODIGOINVENTARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_EI", cODIGOINVENTARIOParameter);
        }
    
        public virtual int EliminarME(string cODIGOINVENTARIO)
        {
            var cODIGOINVENTARIOParameter = cODIGOINVENTARIO != null ?
                new ObjectParameter("CODIGOINVENTARIO", cODIGOINVENTARIO) :
                new ObjectParameter("CODIGOINVENTARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EliminarME", cODIGOINVENTARIOParameter);
        }
    
        public virtual int INSERT_EQUIPO_ME(Nullable<int> iD_DEPTO_ODEF, Nullable<int> nUMERO_REFERENCIA, string cODIGO_INVENTARIO, Nullable<System.DateTime> fECHA_COMPRA, Nullable<System.DateTime> mES_DEPRECIACION, Nullable<int> iD_PROVEEDOR, string tIPO_MOBILIARIO, Nullable<int> iD_MARCA, string tIPO_MATERIAL, string cOLOR, Nullable<int> dIVISIONES_GAVETAS, string mODELO, string nUMERO_SERIE, string uBICACION, Nullable<int> iD_EMPLEADO, string cONDICION_ACTUAL, string uSUARIO_RESPONSABLE, string eSTADO)
        {
            var iD_DEPTO_ODEFParameter = iD_DEPTO_ODEF.HasValue ?
                new ObjectParameter("ID_DEPTO_ODEF", iD_DEPTO_ODEF) :
                new ObjectParameter("ID_DEPTO_ODEF", typeof(int));
    
            var nUMERO_REFERENCIAParameter = nUMERO_REFERENCIA.HasValue ?
                new ObjectParameter("NUMERO_REFERENCIA", nUMERO_REFERENCIA) :
                new ObjectParameter("NUMERO_REFERENCIA", typeof(int));
    
            var cODIGO_INVENTARIOParameter = cODIGO_INVENTARIO != null ?
                new ObjectParameter("CODIGO_INVENTARIO", cODIGO_INVENTARIO) :
                new ObjectParameter("CODIGO_INVENTARIO", typeof(string));
    
            var fECHA_COMPRAParameter = fECHA_COMPRA.HasValue ?
                new ObjectParameter("FECHA_COMPRA", fECHA_COMPRA) :
                new ObjectParameter("FECHA_COMPRA", typeof(System.DateTime));
    
            var mES_DEPRECIACIONParameter = mES_DEPRECIACION.HasValue ?
                new ObjectParameter("MES_DEPRECIACION", mES_DEPRECIACION) :
                new ObjectParameter("MES_DEPRECIACION", typeof(System.DateTime));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR.HasValue ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(int));
    
            var tIPO_MOBILIARIOParameter = tIPO_MOBILIARIO != null ?
                new ObjectParameter("TIPO_MOBILIARIO", tIPO_MOBILIARIO) :
                new ObjectParameter("TIPO_MOBILIARIO", typeof(string));
    
            var iD_MARCAParameter = iD_MARCA.HasValue ?
                new ObjectParameter("ID_MARCA", iD_MARCA) :
                new ObjectParameter("ID_MARCA", typeof(int));
    
            var tIPO_MATERIALParameter = tIPO_MATERIAL != null ?
                new ObjectParameter("TIPO_MATERIAL", tIPO_MATERIAL) :
                new ObjectParameter("TIPO_MATERIAL", typeof(string));
    
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var dIVISIONES_GAVETASParameter = dIVISIONES_GAVETAS.HasValue ?
                new ObjectParameter("DIVISIONES_GAVETAS", dIVISIONES_GAVETAS) :
                new ObjectParameter("DIVISIONES_GAVETAS", typeof(int));
    
            var mODELOParameter = mODELO != null ?
                new ObjectParameter("MODELO", mODELO) :
                new ObjectParameter("MODELO", typeof(string));
    
            var nUMERO_SERIEParameter = nUMERO_SERIE != null ?
                new ObjectParameter("NUMERO_SERIE", nUMERO_SERIE) :
                new ObjectParameter("NUMERO_SERIE", typeof(string));
    
            var uBICACIONParameter = uBICACION != null ?
                new ObjectParameter("UBICACION", uBICACION) :
                new ObjectParameter("UBICACION", typeof(string));
    
            var iD_EMPLEADOParameter = iD_EMPLEADO.HasValue ?
                new ObjectParameter("ID_EMPLEADO", iD_EMPLEADO) :
                new ObjectParameter("ID_EMPLEADO", typeof(int));
    
            var cONDICION_ACTUALParameter = cONDICION_ACTUAL != null ?
                new ObjectParameter("CONDICION_ACTUAL", cONDICION_ACTUAL) :
                new ObjectParameter("CONDICION_ACTUAL", typeof(string));
    
            var uSUARIO_RESPONSABLEParameter = uSUARIO_RESPONSABLE != null ?
                new ObjectParameter("USUARIO_RESPONSABLE", uSUARIO_RESPONSABLE) :
                new ObjectParameter("USUARIO_RESPONSABLE", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_EQUIPO_ME", iD_DEPTO_ODEFParameter, nUMERO_REFERENCIAParameter, cODIGO_INVENTARIOParameter, fECHA_COMPRAParameter, mES_DEPRECIACIONParameter, iD_PROVEEDORParameter, tIPO_MOBILIARIOParameter, iD_MARCAParameter, tIPO_MATERIALParameter, cOLORParameter, dIVISIONES_GAVETASParameter, mODELOParameter, nUMERO_SERIEParameter, uBICACIONParameter, iD_EMPLEADOParameter, cONDICION_ACTUALParameter, uSUARIO_RESPONSABLEParameter, eSTADOParameter);
        }
    
        public virtual int INSERT_INVENTARIO_INFORMATICA(Nullable<int> iD_DEPTO, Nullable<int> nUMERO_REFERENCIA, string cODIGO_INVENTARIO, Nullable<System.DateTime> fECHA_COMPRA, Nullable<System.DateTime> mES_DEPRECIACION, Nullable<int> iD_PROVEEDOR, Nullable<int> iD_TIPO_EQUIPO, Nullable<int> iD_MARCA, string cOLOR, string mODELO, string nUMERO_SERIE, string tIPO_PROCESADOR, string dISQUETERA, string lECTOR_DVD, string lECTOR_SD_MMC, string pARLANTES_EXTERNOS, string mONITOR_COLOR, string mONITOR_SERIE, string mONITOR_TAMANIO, string mONITOR_TIPO, string tECLADO_COLOR, string tECLADO_MODELO, string mOUSE_COLOR, string uBICACION, Nullable<int> iD_EMPLEADO, string cONDICION_ACTUAL, string uSUARIO_RESPONSABLE, string eSTADO)
        {
            var iD_DEPTOParameter = iD_DEPTO.HasValue ?
                new ObjectParameter("ID_DEPTO", iD_DEPTO) :
                new ObjectParameter("ID_DEPTO", typeof(int));
    
            var nUMERO_REFERENCIAParameter = nUMERO_REFERENCIA.HasValue ?
                new ObjectParameter("NUMERO_REFERENCIA", nUMERO_REFERENCIA) :
                new ObjectParameter("NUMERO_REFERENCIA", typeof(int));
    
            var cODIGO_INVENTARIOParameter = cODIGO_INVENTARIO != null ?
                new ObjectParameter("CODIGO_INVENTARIO", cODIGO_INVENTARIO) :
                new ObjectParameter("CODIGO_INVENTARIO", typeof(string));
    
            var fECHA_COMPRAParameter = fECHA_COMPRA.HasValue ?
                new ObjectParameter("FECHA_COMPRA", fECHA_COMPRA) :
                new ObjectParameter("FECHA_COMPRA", typeof(System.DateTime));
    
            var mES_DEPRECIACIONParameter = mES_DEPRECIACION.HasValue ?
                new ObjectParameter("MES_DEPRECIACION", mES_DEPRECIACION) :
                new ObjectParameter("MES_DEPRECIACION", typeof(System.DateTime));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR.HasValue ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(int));
    
            var iD_TIPO_EQUIPOParameter = iD_TIPO_EQUIPO.HasValue ?
                new ObjectParameter("ID_TIPO_EQUIPO", iD_TIPO_EQUIPO) :
                new ObjectParameter("ID_TIPO_EQUIPO", typeof(int));
    
            var iD_MARCAParameter = iD_MARCA.HasValue ?
                new ObjectParameter("ID_MARCA", iD_MARCA) :
                new ObjectParameter("ID_MARCA", typeof(int));
    
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var mODELOParameter = mODELO != null ?
                new ObjectParameter("MODELO", mODELO) :
                new ObjectParameter("MODELO", typeof(string));
    
            var nUMERO_SERIEParameter = nUMERO_SERIE != null ?
                new ObjectParameter("NUMERO_SERIE", nUMERO_SERIE) :
                new ObjectParameter("NUMERO_SERIE", typeof(string));
    
            var tIPO_PROCESADORParameter = tIPO_PROCESADOR != null ?
                new ObjectParameter("TIPO_PROCESADOR", tIPO_PROCESADOR) :
                new ObjectParameter("TIPO_PROCESADOR", typeof(string));
    
            var dISQUETERAParameter = dISQUETERA != null ?
                new ObjectParameter("DISQUETERA", dISQUETERA) :
                new ObjectParameter("DISQUETERA", typeof(string));
    
            var lECTOR_DVDParameter = lECTOR_DVD != null ?
                new ObjectParameter("LECTOR_DVD", lECTOR_DVD) :
                new ObjectParameter("LECTOR_DVD", typeof(string));
    
            var lECTOR_SD_MMCParameter = lECTOR_SD_MMC != null ?
                new ObjectParameter("LECTOR_SD_MMC", lECTOR_SD_MMC) :
                new ObjectParameter("LECTOR_SD_MMC", typeof(string));
    
            var pARLANTES_EXTERNOSParameter = pARLANTES_EXTERNOS != null ?
                new ObjectParameter("PARLANTES_EXTERNOS", pARLANTES_EXTERNOS) :
                new ObjectParameter("PARLANTES_EXTERNOS", typeof(string));
    
            var mONITOR_COLORParameter = mONITOR_COLOR != null ?
                new ObjectParameter("MONITOR_COLOR", mONITOR_COLOR) :
                new ObjectParameter("MONITOR_COLOR", typeof(string));
    
            var mONITOR_SERIEParameter = mONITOR_SERIE != null ?
                new ObjectParameter("MONITOR_SERIE", mONITOR_SERIE) :
                new ObjectParameter("MONITOR_SERIE", typeof(string));
    
            var mONITOR_TAMANIOParameter = mONITOR_TAMANIO != null ?
                new ObjectParameter("MONITOR_TAMANIO", mONITOR_TAMANIO) :
                new ObjectParameter("MONITOR_TAMANIO", typeof(string));
    
            var mONITOR_TIPOParameter = mONITOR_TIPO != null ?
                new ObjectParameter("MONITOR_TIPO", mONITOR_TIPO) :
                new ObjectParameter("MONITOR_TIPO", typeof(string));
    
            var tECLADO_COLORParameter = tECLADO_COLOR != null ?
                new ObjectParameter("TECLADO_COLOR", tECLADO_COLOR) :
                new ObjectParameter("TECLADO_COLOR", typeof(string));
    
            var tECLADO_MODELOParameter = tECLADO_MODELO != null ?
                new ObjectParameter("TECLADO_MODELO", tECLADO_MODELO) :
                new ObjectParameter("TECLADO_MODELO", typeof(string));
    
            var mOUSE_COLORParameter = mOUSE_COLOR != null ?
                new ObjectParameter("MOUSE_COLOR", mOUSE_COLOR) :
                new ObjectParameter("MOUSE_COLOR", typeof(string));
    
            var uBICACIONParameter = uBICACION != null ?
                new ObjectParameter("UBICACION", uBICACION) :
                new ObjectParameter("UBICACION", typeof(string));
    
            var iD_EMPLEADOParameter = iD_EMPLEADO.HasValue ?
                new ObjectParameter("ID_EMPLEADO", iD_EMPLEADO) :
                new ObjectParameter("ID_EMPLEADO", typeof(int));
    
            var cONDICION_ACTUALParameter = cONDICION_ACTUAL != null ?
                new ObjectParameter("CONDICION_ACTUAL", cONDICION_ACTUAL) :
                new ObjectParameter("CONDICION_ACTUAL", typeof(string));
    
            var uSUARIO_RESPONSABLEParameter = uSUARIO_RESPONSABLE != null ?
                new ObjectParameter("USUARIO_RESPONSABLE", uSUARIO_RESPONSABLE) :
                new ObjectParameter("USUARIO_RESPONSABLE", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_INVENTARIO_INFORMATICA", iD_DEPTOParameter, nUMERO_REFERENCIAParameter, cODIGO_INVENTARIOParameter, fECHA_COMPRAParameter, mES_DEPRECIACIONParameter, iD_PROVEEDORParameter, iD_TIPO_EQUIPOParameter, iD_MARCAParameter, cOLORParameter, mODELOParameter, nUMERO_SERIEParameter, tIPO_PROCESADORParameter, dISQUETERAParameter, lECTOR_DVDParameter, lECTOR_SD_MMCParameter, pARLANTES_EXTERNOSParameter, mONITOR_COLORParameter, mONITOR_SERIEParameter, mONITOR_TAMANIOParameter, mONITOR_TIPOParameter, tECLADO_COLORParameter, tECLADO_MODELOParameter, mOUSE_COLORParameter, uBICACIONParameter, iD_EMPLEADOParameter, cONDICION_ACTUALParameter, uSUARIO_RESPONSABLEParameter, eSTADOParameter);
        }
    
        public virtual int InsertareTomaEI(string departamento, string usuario_Responsable, Nullable<System.DateTime> fecha_Toma_Inventario, string codigo_Inventario)
        {
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var usuario_ResponsableParameter = usuario_Responsable != null ?
                new ObjectParameter("Usuario_Responsable", usuario_Responsable) :
                new ObjectParameter("Usuario_Responsable", typeof(string));
    
            var fecha_Toma_InventarioParameter = fecha_Toma_Inventario.HasValue ?
                new ObjectParameter("Fecha_Toma_Inventario", fecha_Toma_Inventario) :
                new ObjectParameter("Fecha_Toma_Inventario", typeof(System.DateTime));
    
            var codigo_InventarioParameter = codigo_Inventario != null ?
                new ObjectParameter("Codigo_Inventario", codigo_Inventario) :
                new ObjectParameter("Codigo_Inventario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertareTomaEI", departamentoParameter, usuario_ResponsableParameter, fecha_Toma_InventarioParameter, codigo_InventarioParameter);
        }
    
        public virtual int MODIFICAR_ME(string cODIGO_INVENTARIO, string nUMERO_SERIE, string tIPO_MATERIAL, string uBICACION, string cONDICION_ACTUAL, string uSUARIO_RESPONSABLE)
        {
            var cODIGO_INVENTARIOParameter = cODIGO_INVENTARIO != null ?
                new ObjectParameter("CODIGO_INVENTARIO", cODIGO_INVENTARIO) :
                new ObjectParameter("CODIGO_INVENTARIO", typeof(string));
    
            var nUMERO_SERIEParameter = nUMERO_SERIE != null ?
                new ObjectParameter("NUMERO_SERIE", nUMERO_SERIE) :
                new ObjectParameter("NUMERO_SERIE", typeof(string));
    
            var tIPO_MATERIALParameter = tIPO_MATERIAL != null ?
                new ObjectParameter("TIPO_MATERIAL", tIPO_MATERIAL) :
                new ObjectParameter("TIPO_MATERIAL", typeof(string));
    
            var uBICACIONParameter = uBICACION != null ?
                new ObjectParameter("UBICACION", uBICACION) :
                new ObjectParameter("UBICACION", typeof(string));
    
            var cONDICION_ACTUALParameter = cONDICION_ACTUAL != null ?
                new ObjectParameter("CONDICION_ACTUAL", cONDICION_ACTUAL) :
                new ObjectParameter("CONDICION_ACTUAL", typeof(string));
    
            var uSUARIO_RESPONSABLEParameter = uSUARIO_RESPONSABLE != null ?
                new ObjectParameter("USUARIO_RESPONSABLE", uSUARIO_RESPONSABLE) :
                new ObjectParameter("USUARIO_RESPONSABLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICAR_ME", cODIGO_INVENTARIOParameter, nUMERO_SERIEParameter, tIPO_MATERIALParameter, uBICACIONParameter, cONDICION_ACTUALParameter, uSUARIO_RESPONSABLEParameter);
        }
    
        public virtual int ModificarEI(string cODIGO_INVENTARIO, string nUMERO_SERIE, string pARLANTES_EXTERNOS, string uBICACION, string cONDICION_ACTUAL, string uSUARIO_RESPONSABLE)
        {
            var cODIGO_INVENTARIOParameter = cODIGO_INVENTARIO != null ?
                new ObjectParameter("CODIGO_INVENTARIO", cODIGO_INVENTARIO) :
                new ObjectParameter("CODIGO_INVENTARIO", typeof(string));
    
            var nUMERO_SERIEParameter = nUMERO_SERIE != null ?
                new ObjectParameter("NUMERO_SERIE", nUMERO_SERIE) :
                new ObjectParameter("NUMERO_SERIE", typeof(string));
    
            var pARLANTES_EXTERNOSParameter = pARLANTES_EXTERNOS != null ?
                new ObjectParameter("PARLANTES_EXTERNOS", pARLANTES_EXTERNOS) :
                new ObjectParameter("PARLANTES_EXTERNOS", typeof(string));
    
            var uBICACIONParameter = uBICACION != null ?
                new ObjectParameter("UBICACION", uBICACION) :
                new ObjectParameter("UBICACION", typeof(string));
    
            var cONDICION_ACTUALParameter = cONDICION_ACTUAL != null ?
                new ObjectParameter("CONDICION_ACTUAL", cONDICION_ACTUAL) :
                new ObjectParameter("CONDICION_ACTUAL", typeof(string));
    
            var uSUARIO_RESPONSABLEParameter = uSUARIO_RESPONSABLE != null ?
                new ObjectParameter("USUARIO_RESPONSABLE", uSUARIO_RESPONSABLE) :
                new ObjectParameter("USUARIO_RESPONSABLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModificarEI", cODIGO_INVENTARIOParameter, nUMERO_SERIEParameter, pARLANTES_EXTERNOSParameter, uBICACIONParameter, cONDICION_ACTUALParameter, uSUARIO_RESPONSABLEParameter);
        }
    
        public virtual int SP_ActivosSelect(string cODIGO_INVENTARIO)
        {
            var cODIGO_INVENTARIOParameter = cODIGO_INVENTARIO != null ?
                new ObjectParameter("CODIGO_INVENTARIO", cODIGO_INVENTARIO) :
                new ObjectParameter("CODIGO_INVENTARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActivosSelect", cODIGO_INVENTARIOParameter);
        }
    
        public virtual int sp_CalculoDepreciacion(Nullable<System.DateTime> fechacierre, string usuario)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculoDepreciacion", fechacierreParameter, usuarioParameter);
        }
    
        public virtual int sp_CalculoDepreciacionAA(Nullable<System.DateTime> fechacierre, string usuario)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculoDepreciacionAA", fechacierreParameter, usuarioParameter);
        }
    
        public virtual int sp_CalculoDepreciacionAP(Nullable<System.DateTime> fechacierre, string usuario)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculoDepreciacionAP", fechacierreParameter, usuarioParameter);
        }
    
        public virtual int sp_CalculoDepreciacionED(Nullable<System.DateTime> fechacierre, string usuario)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculoDepreciacionED", fechacierreParameter, usuarioParameter);
        }
    
        public virtual int sp_CalculoDepreciacionEI(Nullable<System.DateTime> fechacierre, string usuario)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculoDepreciacionEI", fechacierreParameter, usuarioParameter);
        }
    
        public virtual int sp_CalculoDepreciacionVE(Nullable<System.DateTime> fechacierre, string usuario)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculoDepreciacionVE", fechacierreParameter, usuarioParameter);
        }
    
        public virtual int sp_CalculoReserva(Nullable<System.DateTime> fechacierre, string usuario)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculoReserva", fechacierreParameter, usuarioParameter);
        }
    
        public virtual int sp_CopiaHistoricaAA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CopiaHistoricaAA");
        }
    
        public virtual int sp_CopiaHistoricaAP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CopiaHistoricaAP");
        }
    
        public virtual int sp_CopiaHistoricaED()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CopiaHistoricaED");
        }
    
        public virtual int sp_CopiaHistoricaEI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CopiaHistoricaEI");
        }
    
        public virtual int sp_CopiaHistoricaME()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CopiaHistoricaME");
        }
    
        public virtual int sp_CopiaHistoricaRE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CopiaHistoricaRE");
        }
    
        public virtual int sp_CopiaHistoricaVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CopiaHistoricaVE");
        }
    
        public virtual int sp_DepreciacionIndividualAA(Nullable<System.DateTime> fechacierre, string usuario, Nullable<int> id_agen, Nullable<int> id_me)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var id_agenParameter = id_agen.HasValue ?
                new ObjectParameter("id_agen", id_agen) :
                new ObjectParameter("id_agen", typeof(int));
    
            var id_meParameter = id_me.HasValue ?
                new ObjectParameter("id_me", id_me) :
                new ObjectParameter("id_me", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepreciacionIndividualAA", fechacierreParameter, usuarioParameter, id_agenParameter, id_meParameter);
        }
    
        public virtual int sp_DepreciacionIndividualAP(Nullable<System.DateTime> fechacierre, string usuario, Nullable<int> id_agen, Nullable<int> id_me)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var id_agenParameter = id_agen.HasValue ?
                new ObjectParameter("id_agen", id_agen) :
                new ObjectParameter("id_agen", typeof(int));
    
            var id_meParameter = id_me.HasValue ?
                new ObjectParameter("id_me", id_me) :
                new ObjectParameter("id_me", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepreciacionIndividualAP", fechacierreParameter, usuarioParameter, id_agenParameter, id_meParameter);
        }
    
        public virtual int sp_DepreciacionIndividualED(Nullable<System.DateTime> fechacierre, string usuario, Nullable<int> id_agen, Nullable<int> id_ed)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var id_agenParameter = id_agen.HasValue ?
                new ObjectParameter("id_agen", id_agen) :
                new ObjectParameter("id_agen", typeof(int));
    
            var id_edParameter = id_ed.HasValue ?
                new ObjectParameter("id_ed", id_ed) :
                new ObjectParameter("id_ed", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepreciacionIndividualED", fechacierreParameter, usuarioParameter, id_agenParameter, id_edParameter);
        }
    
        public virtual int sp_DepreciacionIndividualEI(Nullable<System.DateTime> fechacierre, string usuario, Nullable<int> id_depto, string cod_inv, string num_ref)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var id_deptoParameter = id_depto.HasValue ?
                new ObjectParameter("id_depto", id_depto) :
                new ObjectParameter("id_depto", typeof(int));
    
            var cod_invParameter = cod_inv != null ?
                new ObjectParameter("cod_inv", cod_inv) :
                new ObjectParameter("cod_inv", typeof(string));
    
            var num_refParameter = num_ref != null ?
                new ObjectParameter("num_ref", num_ref) :
                new ObjectParameter("num_ref", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepreciacionIndividualEI", fechacierreParameter, usuarioParameter, id_deptoParameter, cod_invParameter, num_refParameter);
        }
    
        public virtual int sp_DepreciacionIndividualME(Nullable<System.DateTime> fechacierre, string usuario, Nullable<int> id_depto, string cod_inv, string num_ref)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var id_deptoParameter = id_depto.HasValue ?
                new ObjectParameter("id_depto", id_depto) :
                new ObjectParameter("id_depto", typeof(int));
    
            var cod_invParameter = cod_inv != null ?
                new ObjectParameter("cod_inv", cod_inv) :
                new ObjectParameter("cod_inv", typeof(string));
    
            var num_refParameter = num_ref != null ?
                new ObjectParameter("num_ref", num_ref) :
                new ObjectParameter("num_ref", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepreciacionIndividualME", fechacierreParameter, usuarioParameter, id_deptoParameter, cod_invParameter, num_refParameter);
        }
    
        public virtual int sp_DepreciacionIndividualVE(Nullable<System.DateTime> fechacierre, string usuario, Nullable<int> id_agen, Nullable<int> id_ve)
        {
            var fechacierreParameter = fechacierre.HasValue ?
                new ObjectParameter("fechacierre", fechacierre) :
                new ObjectParameter("fechacierre", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var id_agenParameter = id_agen.HasValue ?
                new ObjectParameter("id_agen", id_agen) :
                new ObjectParameter("id_agen", typeof(int));
    
            var id_veParameter = id_ve.HasValue ?
                new ObjectParameter("id_ve", id_ve) :
                new ObjectParameter("id_ve", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepreciacionIndividualVE", fechacierreParameter, usuarioParameter, id_agenParameter, id_veParameter);
        }
    
        public virtual int SP_INSERTAR_TOMA_ME(string departamento, Nullable<System.DateTime> fecha_Toma_Inventario, string usuario_Responsable, string codigo_Inventario)
        {
            var departamentoParameter = departamento != null ?
                new ObjectParameter("Departamento", departamento) :
                new ObjectParameter("Departamento", typeof(string));
    
            var fecha_Toma_InventarioParameter = fecha_Toma_Inventario.HasValue ?
                new ObjectParameter("Fecha_Toma_Inventario", fecha_Toma_Inventario) :
                new ObjectParameter("Fecha_Toma_Inventario", typeof(System.DateTime));
    
            var usuario_ResponsableParameter = usuario_Responsable != null ?
                new ObjectParameter("Usuario_Responsable", usuario_Responsable) :
                new ObjectParameter("Usuario_Responsable", typeof(string));
    
            var codigo_InventarioParameter = codigo_Inventario != null ?
                new ObjectParameter("Codigo_Inventario", codigo_Inventario) :
                new ObjectParameter("Codigo_Inventario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_TOMA_ME", departamentoParameter, fecha_Toma_InventarioParameter, usuario_ResponsableParameter, codigo_InventarioParameter);
        }
    
        public virtual int SP_InsertarCostoDePEI(Nullable<int> iD_DEPTO_ODEF, Nullable<int> nUMERO_REFERENCIA, string cODIGO_INVENTARIO, Nullable<System.DateTime> fECHA_COMPRA, string nUM_CKE, string nUM_PDA, Nullable<decimal> cOSTO, Nullable<int> vIDA, string uSUARIO, string eSTADO)
        {
            var iD_DEPTO_ODEFParameter = iD_DEPTO_ODEF.HasValue ?
                new ObjectParameter("ID_DEPTO_ODEF", iD_DEPTO_ODEF) :
                new ObjectParameter("ID_DEPTO_ODEF", typeof(int));
    
            var nUMERO_REFERENCIAParameter = nUMERO_REFERENCIA.HasValue ?
                new ObjectParameter("NUMERO_REFERENCIA", nUMERO_REFERENCIA) :
                new ObjectParameter("NUMERO_REFERENCIA", typeof(int));
    
            var cODIGO_INVENTARIOParameter = cODIGO_INVENTARIO != null ?
                new ObjectParameter("CODIGO_INVENTARIO", cODIGO_INVENTARIO) :
                new ObjectParameter("CODIGO_INVENTARIO", typeof(string));
    
            var fECHA_COMPRAParameter = fECHA_COMPRA.HasValue ?
                new ObjectParameter("FECHA_COMPRA", fECHA_COMPRA) :
                new ObjectParameter("FECHA_COMPRA", typeof(System.DateTime));
    
            var nUM_CKEParameter = nUM_CKE != null ?
                new ObjectParameter("NUM_CKE", nUM_CKE) :
                new ObjectParameter("NUM_CKE", typeof(string));
    
            var nUM_PDAParameter = nUM_PDA != null ?
                new ObjectParameter("NUM_PDA", nUM_PDA) :
                new ObjectParameter("NUM_PDA", typeof(string));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var vIDAParameter = vIDA.HasValue ?
                new ObjectParameter("VIDA", vIDA) :
                new ObjectParameter("VIDA", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarCostoDePEI", iD_DEPTO_ODEFParameter, nUMERO_REFERENCIAParameter, cODIGO_INVENTARIOParameter, fECHA_COMPRAParameter, nUM_CKEParameter, nUM_PDAParameter, cOSTOParameter, vIDAParameter, uSUARIOParameter, eSTADOParameter);
        }
    
        public virtual int SP_InsertarDDME(Nullable<int> iD_DEPTO_ODEF, Nullable<int> nUMERO_REFERENCIA, string cODIGO_INVENTARIO, Nullable<System.DateTime> fECHA_COMPRA, string nUM_CKE, string nUM_PDA, Nullable<decimal> cOSTO, Nullable<int> vIDA, string uSUARIO, string eSTADO)
        {
            var iD_DEPTO_ODEFParameter = iD_DEPTO_ODEF.HasValue ?
                new ObjectParameter("ID_DEPTO_ODEF", iD_DEPTO_ODEF) :
                new ObjectParameter("ID_DEPTO_ODEF", typeof(int));
    
            var nUMERO_REFERENCIAParameter = nUMERO_REFERENCIA.HasValue ?
                new ObjectParameter("NUMERO_REFERENCIA", nUMERO_REFERENCIA) :
                new ObjectParameter("NUMERO_REFERENCIA", typeof(int));
    
            var cODIGO_INVENTARIOParameter = cODIGO_INVENTARIO != null ?
                new ObjectParameter("CODIGO_INVENTARIO", cODIGO_INVENTARIO) :
                new ObjectParameter("CODIGO_INVENTARIO", typeof(string));
    
            var fECHA_COMPRAParameter = fECHA_COMPRA.HasValue ?
                new ObjectParameter("FECHA_COMPRA", fECHA_COMPRA) :
                new ObjectParameter("FECHA_COMPRA", typeof(System.DateTime));
    
            var nUM_CKEParameter = nUM_CKE != null ?
                new ObjectParameter("NUM_CKE", nUM_CKE) :
                new ObjectParameter("NUM_CKE", typeof(string));
    
            var nUM_PDAParameter = nUM_PDA != null ?
                new ObjectParameter("NUM_PDA", nUM_PDA) :
                new ObjectParameter("NUM_PDA", typeof(string));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var vIDAParameter = vIDA.HasValue ?
                new ObjectParameter("VIDA", vIDA) :
                new ObjectParameter("VIDA", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarDDME", iD_DEPTO_ODEFParameter, nUMERO_REFERENCIAParameter, cODIGO_INVENTARIOParameter, fECHA_COMPRAParameter, nUM_CKEParameter, nUM_PDAParameter, cOSTOParameter, vIDAParameter, uSUARIOParameter, eSTADOParameter);
        }
    }
}
