//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion.conexion.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE_PROVEEDOR { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CONTACTO { get; set; }
        public string TELEFONO_CONTACTO { get; set; }
        public string USUARIO_RESPONSALE { get; set; }
        public string ESTADO { get; set; }
    }
}
